/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Pranil
 */
public class Create_Account_Page extends javax.swing.JFrame {

    /**
     * Creates new form Create_Account_Page
     */
    public Create_Account_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL2 = new javax.swing.JLabel();
        LBL3 = new javax.swing.JLabel();
        LBL4 = new javax.swing.JLabel();
        LBL5 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        TF4 = new javax.swing.JTextField();
        LBL6 = new javax.swing.JLabel();
        LBL7 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        LBL8 = new javax.swing.JLabel();
        JCB1 = new javax.swing.JComboBox<>();
        LBL9 = new javax.swing.JLabel();
        TF6 = new javax.swing.JTextField();
        LBL10 = new javax.swing.JLabel();
        JDC1 = new com.toedter.calendar.JDateChooser();
        LBL11 = new javax.swing.JLabel();
        TF7 = new javax.swing.JTextField();
        LBL12 = new javax.swing.JLabel();
        LBL13 = new javax.swing.JLabel();
        JB1 = new javax.swing.JButton();
        LBL14 = new javax.swing.JLabel();
        LBL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setMinimumSize(new java.awt.Dimension(1440, 855));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        LBL2.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        LBL2.setText("Create Account");
        getContentPane().add(LBL2);
        LBL2.setBounds(590, 90, 270, 40);

        LBL3.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL3.setText("Enter First Name * ");
        getContentPane().add(LBL3);
        LBL3.setBounds(490, 160, 190, 38);

        LBL4.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL4.setText("Enter Last Name * ");
        getContentPane().add(LBL4);
        LBL4.setBounds(490, 220, 190, 38);

        LBL5.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL5.setText("Enter Email ID *");
        getContentPane().add(LBL5);
        LBL5.setBounds(490, 280, 190, 38);

        TF1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF1.setText("  First Name");
        TF1.setPreferredSize(new java.awt.Dimension(124, 38));
        TF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF1MouseExited(evt);
            }
        });
        getContentPane().add(TF1);
        TF1.setBounds(710, 160, 230, 38);

        TF2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF2.setText("  Last Name");
        TF2.setPreferredSize(new java.awt.Dimension(124, 38));
        TF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF2MouseExited(evt);
            }
        });
        getContentPane().add(TF2);
        TF2.setBounds(710, 220, 230, 38);

        TF3.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF3.setText("  Email ID");
        TF3.setPreferredSize(new java.awt.Dimension(124, 38));
        TF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF3MouseExited(evt);
            }
        });
        getContentPane().add(TF3);
        TF3.setBounds(710, 280, 230, 38);

        TF4.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF4.setText("  Password");
        TF4.setPreferredSize(new java.awt.Dimension(124, 38));
        TF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF4MouseExited(evt);
            }
        });
        getContentPane().add(TF4);
        TF4.setBounds(710, 340, 230, 38);

        LBL6.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL6.setForeground(new java.awt.Color(255, 255, 255));
        LBL6.setText("Enter Password *");
        getContentPane().add(LBL6);
        LBL6.setBounds(490, 340, 190, 38);

        LBL7.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL7.setForeground(new java.awt.Color(255, 255, 255));
        LBL7.setText("Re-Type Password *");
        getContentPane().add(LBL7);
        LBL7.setBounds(490, 400, 200, 38);

        TF5.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF5.setText("  Re-Type Password");
        TF5.setPreferredSize(new java.awt.Dimension(124, 38));
        TF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF5MouseExited(evt);
            }
        });
        getContentPane().add(TF5);
        TF5.setBounds(710, 400, 230, 38);

        LBL8.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL8.setForeground(new java.awt.Color(255, 255, 255));
        LBL8.setText("Security Question *");
        getContentPane().add(LBL8);
        LBL8.setBounds(490, 460, 200, 38);

        JCB1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        JCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Favourite Actor/Actress.", "Favourite Teacher.", "Favourite Dish.", "Favourite Place.", "Favourite Singer" }));
        getContentPane().add(JCB1);
        JCB1.setBounds(710, 460, 230, 38);

        LBL9.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL9.setForeground(new java.awt.Color(255, 255, 255));
        LBL9.setText("Security Answer *");
        getContentPane().add(LBL9);
        LBL9.setBounds(490, 520, 200, 38);

        TF6.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF6.setText("  Answer");
        TF6.setPreferredSize(new java.awt.Dimension(124, 38));
        TF6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF6MouseExited(evt);
            }
        });
        getContentPane().add(TF6);
        TF6.setBounds(710, 520, 230, 38);

        LBL10.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL10.setForeground(new java.awt.Color(255, 255, 255));
        LBL10.setText("Date Of Birth *");
        getContentPane().add(LBL10);
        LBL10.setBounds(490, 580, 200, 38);

        JDC1.setToolTipText("SELECT THE ARRIIVAL DATE");
        getContentPane().add(JDC1);
        JDC1.setBounds(710, 580, 230, 38);

        LBL11.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        LBL11.setForeground(new java.awt.Color(255, 255, 255));
        LBL11.setText("Contact No. *");
        getContentPane().add(LBL11);
        LBL11.setBounds(490, 640, 200, 38);

        TF7.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF7.setText("  Contact No.");
        TF7.setPreferredSize(new java.awt.Dimension(124, 38));
        TF7.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TF7CaretUpdate(evt);
            }
        });
        TF7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF7MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF7MouseExited(evt);
            }
        });
        getContentPane().add(TF7);
        TF7.setBounds(710, 640, 230, 38);
        TF7.getAccessibleContext().setAccessibleDescription("");

        LBL12.setBackground(new java.awt.Color(0, 153, 51));
        LBL12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Correct.jpg"))); // NOI18N
        getContentPane().add(LBL12);
        LBL12.setBounds(940, 640, 40, 38);

        LBL13.setBackground(new java.awt.Color(153, 0, 0));
        LBL13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Incorrect.jpg"))); // NOI18N
        getContentPane().add(LBL13);
        LBL13.setBounds(940, 640, 40, 38);

        JB1.setBackground(new java.awt.Color(255, 255, 255));
        JB1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        JB1.setText("SUBMIT");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JB1);
        JB1.setBounds(660, 710, 140, 40);

        LBL14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Button-Back.jpg"))); // NOI18N
        LBL14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL14MouseClicked(evt);
            }
        });
        getContentPane().add(LBL14);
        LBL14.setBounds(10, 10, 40, 40);

        LBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Background Image 2.jpg"))); // NOI18N
        getContentPane().add(LBL1);
        LBL1.setBounds(0, 0, 1440, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseClicked
        TF1.setText(""); 
    }//GEN-LAST:event_TF1MouseClicked

    private void TF1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseExited
        String FN = TF1.getText();
        if (FN.isEmpty())
            TF1.setText("  First Name");
    }//GEN-LAST:event_TF1MouseExited

    private void TF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF2MouseClicked
        TF2.setText("");
    }//GEN-LAST:event_TF2MouseClicked

    private void TF2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF2MouseExited
        String LN = TF2.getText();
        if (LN.isEmpty())
            TF2.setText("  Last Name");
    }//GEN-LAST:event_TF2MouseExited

    private void TF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF3MouseClicked
        TF3.setText("");
    }//GEN-LAST:event_TF3MouseClicked

    private void TF3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF3MouseExited
        String EID = TF3.getText();
        if (EID.isEmpty())
            TF3.setText("  Email ID");
    }//GEN-LAST:event_TF3MouseExited

    private void TF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF4MouseClicked
        TF4.setText("");
    }//GEN-LAST:event_TF4MouseClicked

    private void TF4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF4MouseExited
        String PW = TF4.getText();
        if (PW.isEmpty())
            TF4.setText("  Password");
    }//GEN-LAST:event_TF4MouseExited

    private void TF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF5MouseClicked
        TF5.setText("");
    }//GEN-LAST:event_TF5MouseClicked

    private void TF5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF5MouseExited
        String RTP = TF5.getText();
        if (RTP.isEmpty())
            TF5.setText("  Re-Type Password");    
    }//GEN-LAST:event_TF5MouseExited

    private void TF6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF6MouseClicked
        TF6.setText(""); 
    }//GEN-LAST:event_TF6MouseClicked

    private void TF6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF6MouseExited
        String AN = TF6.getText();
        if (AN.isEmpty())
            TF6.setText("  Answer");
    }//GEN-LAST:event_TF6MouseExited

    private void TF7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF7MouseClicked
        TF7.setText(""); 
    }//GEN-LAST:event_TF7MouseClicked

    private void TF7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF7MouseExited
        String CN = TF7.getText();
        if (CN.isEmpty())
            TF7.setText("  Contact No.");       
    }//GEN-LAST:event_TF7MouseExited

    private void TF7CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TF7CaretUpdate
        int L = TF7.getText().length();
        
        if (L == 10)
        {
            LBL12.setVisible(true);
            LBL13.setVisible(false);
        }
        else
        {
            LBL13.setVisible(true);
            LBL12.setVisible(false);
        }
    }//GEN-LAST:event_TF7CaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LBL12.setVisible(false);
        LBL13.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
    SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
    String FN = TF1.getText();
    String LN = TF2.getText();
    String EID = TF3.getText();
    String PD = TF4.getText();
    String RTP = TF5.getText();
    String SQ = (String) JCB1.getSelectedItem();
    String SA = TF6.getText();
    java.util.Date DOB = JDC1.getDate();
    String s1=(String) sdf.format(JDC1.getDate());
    String CN = TF7.getText();
    int L = CN.length();
    
        if (FN.equals("  First Name"))
            JOptionPane.showMessageDialog(this, "Please Enter First Name" , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);
        else if (LN.equals("  Last Name"))
            JOptionPane.showMessageDialog(this, "Please Enter Last Name" , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);
        else if (EID.equals("  Email ID"))
            JOptionPane.showMessageDialog(this, "Please Enter Email ID" , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);         
        else if (PD.equals("  Password"))
            JOptionPane.showMessageDialog(this, "Please Enter Password" , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);           
        else if (RTP.equals("  Re-Type Password"))                
            JOptionPane.showMessageDialog(this, "Please Re-Type Password" , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);
        else if (!(RTP).equals(PD))          
                JOptionPane.showMessageDialog(this, "Please Re-Type Password Correctly" , "Error" , JOptionPane.ERROR_MESSAGE);                                                       
        else if (SA.equals("  Answer"))        
            JOptionPane.showMessageDialog(this, "Please Enter Answer" , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);                  
        else if (CN.equals("  Contact No."))                
            JOptionPane.showMessageDialog(this, "Please Enter Contact No." , "Please enter following entry" , JOptionPane.ERROR_MESSAGE);     
        else if (L==0 || L>=11 || L<10)        
               JOptionPane.showMessageDialog(this, "Contact No. Should be of 10 digit" , "Error" , JOptionPane.ERROR_MESSAGE);
        else
        {    
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection CON = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
                Statement STM = CON.createStatement();
                String QUE = "SELECT EmailID FROM Customer_Information WHERE EmailID = '"+EID+"';";
                ResultSet RS = STM.executeQuery(QUE);
                if (RS.next())
                {
                    String ED = RS.getString("EmailID");
                    if (ED.equals(EID))
                    {
                        JOptionPane.showMessageDialog(this, "Account Already Exist" , "Error" , JOptionPane.ERROR_MESSAGE);
                        Login_Page LP = new Login_Page();
                        LP.setVisible(true);
                        LP.setAlwaysOnTop(true);
                    }
                }
            }
            catch (Exception e)
            {
               JOptionPane.showMessageDialog(this,e.getMessage());
            }
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection CON = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
                Statement STM = CON.createStatement();
                String QUE = "INSERT INTO Customer_Information VALUES ('"+FN+"','"+LN+"','"+EID+"','"+PD+"','"+SQ+"','"+SA+"','"+s1+"','"+CN+"');";
                STM.executeUpdate(QUE);
                JOptionPane.showMessageDialog(null,"Account Created Successfully!!");
                Room_Booking RB = new Room_Booking();
                RB.setVisible(true);
                this.dispose();
            }
            catch (Exception e)
            {
               JOptionPane.showMessageDialog(this,e.getMessage());
            }
        }
    
    }//GEN-LAST:event_JB1ActionPerformed

    private void LBL14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL14MouseClicked
        Login_Page LP = new Login_Page();
        LP.setVisible(true);
    }//GEN-LAST:event_LBL14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create_Account_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create_Account_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create_Account_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create_Account_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create_Account_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JComboBox<String> JCB1;
    private com.toedter.calendar.JDateChooser JDC1;
    private javax.swing.JLabel LBL1;
    private javax.swing.JLabel LBL10;
    private javax.swing.JLabel LBL11;
    private javax.swing.JLabel LBL12;
    private javax.swing.JLabel LBL13;
    private javax.swing.JLabel LBL14;
    private javax.swing.JLabel LBL2;
    private javax.swing.JLabel LBL3;
    private javax.swing.JLabel LBL4;
    private javax.swing.JLabel LBL5;
    private javax.swing.JLabel LBL6;
    private javax.swing.JLabel LBL7;
    private javax.swing.JLabel LBL8;
    private javax.swing.JLabel LBL9;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    // End of variables declaration//GEN-END:variables
}
