/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pranil
 */
public class Forgot_Password_Page extends javax.swing.JFrame {

    /**
     * Creates new form Forgot_Password_Page
     */
    public Forgot_Password_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL2 = new javax.swing.JLabel();
        TF5 = new javax.swing.JTextField();
        LBL3 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        LBL6 = new javax.swing.JLabel();
        TF4 = new javax.swing.JTextField();
        LBL4 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        LBL5 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        LBL7 = new javax.swing.JLabel();
        LBL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 855));
        setMinimumSize(new java.awt.Dimension(1440, 855));
        setPreferredSize(new java.awt.Dimension(1440, 855));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBL2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        LBL2.setText("Security Question");
        LBL2.setEnabled(false);
        getContentPane().add(LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        TF5.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF5.setEnabled(false);
        TF5.setPreferredSize(new java.awt.Dimension(124, 38));
        TF5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF5MouseExited(evt);
            }
        });
        getContentPane().add(TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, 240, -1));

        LBL3.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        LBL3.setText("Security Answer");
        LBL3.setEnabled(false);
        getContentPane().add(LBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        TF1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF1.setEnabled(false);
        TF1.setPreferredSize(new java.awt.Dimension(124, 38));
        TF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF1MouseExited(evt);
            }
        });
        getContentPane().add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 240, -1));

        LBL6.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        LBL6.setText("Enter Email ID");
        getContentPane().add(LBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        TF4.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF4.setPreferredSize(new java.awt.Dimension(124, 38));
        TF4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF4MouseExited(evt);
            }
        });
        TF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF4ActionPerformed(evt);
            }
        });
        getContentPane().add(TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 240, -1));

        LBL4.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        LBL4.setText("Enter New Password");
        LBL4.setEnabled(false);
        getContentPane().add(LBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        TF2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF2.setEnabled(false);
        TF2.setPreferredSize(new java.awt.Dimension(124, 38));
        TF2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF2MouseExited(evt);
            }
        });
        getContentPane().add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 240, -1));

        LBL5.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        LBL5.setText("Re-Type New Password");
        LBL5.setEnabled(false);
        getContentPane().add(LBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, -1));

        TF3.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF3.setEnabled(false);
        TF3.setPreferredSize(new java.awt.Dimension(124, 38));
        TF3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF3MouseExited(evt);
            }
        });
        getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 240, -1));

        JB1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        JB1.setText("ENTER");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 140, 50));

        JB2.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        JB2.setText("RESET PASSWORD");
        JB2.setEnabled(false);
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });
        getContentPane().add(JB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 640, 260, 50));

        LBL7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Button-Back.jpg"))); // NOI18N
        LBL7.setText("jLabel1");
        LBL7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL7MouseClicked(evt);
            }
        });
        getContentPane().add(LBL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        LBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/photo.png"))); // NOI18N
        getContentPane().add(LBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseClicked

    }//GEN-LAST:event_TF1MouseClicked

    private void TF1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseExited

    }//GEN-LAST:event_TF1MouseExited

    private void TF2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2MouseClicked

    private void TF2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2MouseExited

    private void TF3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3MouseClicked

    private void TF3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TF3MouseExited

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        String EID = TF4.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection CON = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
            Statement STM = CON.createStatement();
            String QUE = "SELECT * FROM Customer_Information WHERE EmailID = '"+EID+"';";
            STM.executeQuery(QUE);
            ResultSet RS = STM.executeQuery(QUE);
                if (RS.next())
                {
                    String SQUE = RS.getString("SecurityQuestion");
                    TF5.setText(SQUE);
                    TF1.setEnabled(true);
                    TF2.setEnabled(true);
                    TF3.setEnabled(true);
                    TF4.setEnabled(true);
                    LBL2.setEnabled(true);
                    LBL3.setEnabled(true);
                    LBL4.setEnabled(true);
                    LBL5.setEnabled(true);
                    LBL6.setEnabled(true);
                    JB2.setEnabled(true);
                    TF5.setEnabled(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Incorrect Email ID","Error",JOptionPane.ERROR_MESSAGE);
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_JB1ActionPerformed

    private void TF4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TF4MouseClicked

    private void TF4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TF4MouseExited

    private void TF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF4ActionPerformed

    private void TF5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TF5MouseClicked

    private void TF5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TF5MouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        String SA = TF1.getText();
        String NP = TF2.getText();
        String RTP = TF3.getText();
        String EID = TF4.getText();
        if (RTP.equals(NP))
        {    
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection CON = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
            Statement STM = CON.createStatement();
            String QUE = "SELECT * FROM Customer_Information WHERE EmailID = '"+EID+"';";
            STM.executeQuery(QUE);
            ResultSet RS = STM.executeQuery(QUE);
                if (RS.next())
                {
                    String SQUE = RS.getString("SecurityQuestion");
                    TF5.setText(SQUE);
                    String SANS = RS.getString("SecurityAnswer");
                    if(SANS.equals(SA))
                    {
                        try
                        {
                            Class.forName("java.sql.DriverManager");
                            Connection C = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
                            Statement S = CON.createStatement();
                            String Q = "UPDATE Customer_Information SET Password = '"+NP+"' where EmailID = '"+EID+"';";
                            STM.executeUpdate(Q);
                            JOptionPane.showMessageDialog(this,"Password Update Successfully !!");
                        }
                        catch (Exception e)
                        {
                            JOptionPane.showMessageDialog(this,e.getMessage());
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Security Answer is Improper","Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Please Re-Type Password Correctly","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JB2ActionPerformed

    private void LBL7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL7MouseClicked
        Login_Page LP = new Login_Page();
        LP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LBL7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot_Password_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgot_Password_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JLabel LBL1;
    private javax.swing.JLabel LBL2;
    private javax.swing.JLabel LBL3;
    private javax.swing.JLabel LBL4;
    private javax.swing.JLabel LBL5;
    private javax.swing.JLabel LBL6;
    private javax.swing.JLabel LBL7;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    // End of variables declaration//GEN-END:variables
}
