/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frame;
import AppPackage.AnimationClass;
import java.awt.Color;
import javax.swing.ImageIcon;
/**

import javax.swing.ImageIcon;

 *
 * @author Pranil
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        JP1 = new javax.swing.JPanel();
        LBL1 = new javax.swing.JLabel();
        LBL2 = new javax.swing.JLabel();
        SP1 = new javax.swing.JSeparator();
        JB1 = new javax.swing.JButton();
        LBL4 = new javax.swing.JLabel();
        JP2 = new javax.swing.JPanel();
        LBL25 = new javax.swing.JLabel();
        LBL5 = new javax.swing.JLabel();
        RB1 = new javax.swing.JRadioButton();
        RB2 = new javax.swing.JRadioButton();
        RB3 = new javax.swing.JRadioButton();
        RB4 = new javax.swing.JRadioButton();
        RB5 = new javax.swing.JRadioButton();
        JP3 = new javax.swing.JPanel();
        LBL6 = new javax.swing.JLabel();
        LBL7 = new javax.swing.JLabel();
        LBL8 = new javax.swing.JLabel();
        LBL9 = new javax.swing.JLabel();
        LBL10 = new javax.swing.JLabel();
        JP4 = new javax.swing.JPanel();
        LBL11 = new javax.swing.JLabel();
        LBL12 = new javax.swing.JLabel();
        JSP1 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        JSP2 = new javax.swing.JScrollPane();
        TA2 = new javax.swing.JTextArea();
        JSP3 = new javax.swing.JScrollPane();
        TA3 = new javax.swing.JTextArea();
        JP5 = new javax.swing.JPanel();
        LBL16 = new javax.swing.JLabel();
        LBL17 = new javax.swing.JLabel();
        LBL18 = new javax.swing.JLabel();
        LBL19 = new javax.swing.JLabel();
        LBL20 = new javax.swing.JLabel();
        LBL21 = new javax.swing.JLabel();
        LBL22 = new javax.swing.JLabel();
        LBL23 = new javax.swing.JLabel();
        JBB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" HOME PAGE");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 855));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1440, 855));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1440, 855));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1440, 855));

        JP1.setBackground(new java.awt.Color(255, 255, 255));
        JP1.setMaximumSize(new java.awt.Dimension(1440, 2510));
        JP1.setMinimumSize(new java.awt.Dimension(1440, 2510));
        JP1.setPreferredSize(new java.awt.Dimension(1440, 2510));
        JP1.setLayout(null);

        LBL1.setBackground(new java.awt.Color(255, 255, 255));
        LBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/taj_logo.jpg"))); // NOI18N
        LBL1.setToolTipText("HOTEL TAJ");
        JP1.add(LBL1);
        LBL1.setBounds(320, 10, 60, 50);

        LBL2.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        LBL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Login.jpg"))); // NOI18N
        LBL2.setText("Login / Create Account");
        LBL2.setToolTipText("CLICK TO LOGIN / SIGN UP");
        LBL2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL2MouseClicked(evt);
            }
        });
        JP1.add(LBL2);
        LBL2.setBounds(670, 20, 240, 26);

        SP1.setBackground(new java.awt.Color(0, 0, 0));
        SP1.setForeground(new java.awt.Color(0, 0, 0));
        SP1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        JP1.add(SP1);
        SP1.setBounds(940, 20, 2, 33);

        JB1.setBackground(new java.awt.Color(211, 189, 80));
        JB1.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        JB1.setForeground(new java.awt.Color(137, 102, 51));
        JB1.setText("BOOK MY ROOM");
        JB1.setToolTipText("CLICK TO BOOK ROOM");
        JB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        JP1.add(JB1);
        JB1.setBounds(990, 20, 195, 33);

        LBL4.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        LBL4.setText("THE TAJ MAHAL PALACE, MUMBAI ");
        JP1.add(LBL4);
        LBL4.setBounds(440, 70, 640, 59);

        JP2.setBackground(new java.awt.Color(255, 255, 255));
        JP2.setOpaque(false);

        LBL25.setFont(new java.awt.Font("Signature of the Ancient ", 1, 48)); // NOI18N
        LBL25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/TAJ MAHAL.png"))); // NOI18N
        LBL25.setIconTextGap(5);

        javax.swing.GroupLayout JP2Layout = new javax.swing.GroupLayout(JP2);
        JP2.setLayout(JP2Layout);
        JP2Layout.setHorizontalGroup(
            JP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL25)
                .addContainerGap(1016, Short.MAX_VALUE))
        );
        JP2Layout.setVerticalGroup(
            JP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBL25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JP1.add(JP2);
        JP2.setBounds(0, 132, 1421, 70);
        JP1.add(LBL5);
        LBL5.setBounds(0, 200, 1440, 600);

        RB1.setBackground(new java.awt.Color(137, 102, 51));
        buttonGroup1.add(RB1);
        RB1.setForeground(new java.awt.Color(137, 102, 51));
        RB1.setSelected(true);
        RB1.setToolTipText("CLICK TO SEE NEXT IMAGE");
        RB1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB1ActionPerformed(evt);
            }
        });
        JP1.add(RB1);
        RB1.setBounds(673, 808, 25, 25);

        RB2.setBackground(new java.awt.Color(137, 102, 51));
        buttonGroup1.add(RB2);
        RB2.setForeground(new java.awt.Color(137, 102, 51));
        RB2.setToolTipText("CLICK TO SEE NEXT IMAGE");
        RB2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB2ActionPerformed(evt);
            }
        });
        JP1.add(RB2);
        RB2.setBounds(694, 808, 25, 25);

        RB3.setBackground(new java.awt.Color(137, 102, 51));
        buttonGroup1.add(RB3);
        RB3.setForeground(new java.awt.Color(137, 102, 51));
        RB3.setToolTipText("CLICK TO SEE NEXT IMAGE");
        RB3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB3ActionPerformed(evt);
            }
        });
        JP1.add(RB3);
        RB3.setBounds(715, 808, 25, 25);

        RB4.setBackground(new java.awt.Color(137, 102, 51));
        buttonGroup1.add(RB4);
        RB4.setForeground(new java.awt.Color(137, 102, 51));
        RB4.setToolTipText("CLICK TO SEE NEXT IMAGE");
        RB4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB4ActionPerformed(evt);
            }
        });
        JP1.add(RB4);
        RB4.setBounds(736, 808, 25, 25);

        RB5.setBackground(new java.awt.Color(137, 102, 51));
        buttonGroup1.add(RB5);
        RB5.setForeground(new java.awt.Color(137, 102, 51));
        RB5.setToolTipText("CLICK TO SEE NEXT IMAGE");
        RB5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB5ActionPerformed(evt);
            }
        });
        JP1.add(RB5);
        RB5.setBounds(757, 808, 25, 25);

        JP3.setBackground(new java.awt.Color(255, 255, 255));
        JP3.setOpaque(false);

        LBL6.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        LBL6.setText("EXPERIENCE THE TAJ MAHAL PALACE, MUMBAI  ");

        LBL7.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/UNDERLINE.jpg"))); // NOI18N

        LBL8.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/HISTORY & ARCHITECTURE ICON.jpg"))); // NOI18N

        LBL9.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/TAJ TOWER.jpg"))); // NOI18N

        LBL10.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/HERITAGE WALK ICON.jpg"))); // NOI18N

        javax.swing.GroupLayout JP3Layout = new javax.swing.GroupLayout(JP3);
        JP3.setLayout(JP3Layout);
        JP3Layout.setHorizontalGroup(
            JP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP3Layout.createSequentialGroup()
                .addGroup(JP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(LBL8, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(LBL9, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(LBL10, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP3Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(LBL6))
                    .addGroup(JP3Layout.createSequentialGroup()
                        .addGap(617, 617, 617)
                        .addComponent(LBL7)))
                .addGap(470, 470, 470))
        );
        JP3Layout.setVerticalGroup(
            JP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LBL6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL7)
                .addGap(18, 18, 18)
                .addGroup(JP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBL9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBL8, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        JP1.add(JP3);
        JP3.setBounds(0, 836, 1440, 390);

        JP4.setBackground(new java.awt.Color(255, 255, 255));
        JP4.setOpaque(false);

        LBL11.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        LBL11.setText("HOTEL AMENITIES & FACILITIES  ");

        LBL12.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/UNDERLINE.jpg"))); // NOI18N

        JSP1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        JSP1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        JSP1.setOpaque(false);

        TA1.setEditable(false);
        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TA1.setRows(5);
        TA1.setText("   HOTEL FACILITIES\n\n  • Luxurious rooms & suites with iconic \n    Arabian Sea & Gateway of India views\n  • Options of smoking & non-smoking \n     accommodation\n  • Marble bathrooms withluxury bath \n    amenities OR Five-fixture bathrooms \n    with luxury bath amenities\n  • Complimentary Wi Fi for resident \n     guests\n  • Fine-dining speciality restaurants ­ \n    Wasab i by Morimoto (Japanese),\n    Golden Dragon (Chinese), Masala \n    Kraft (Contemporary Indian) & Sauk \n    (Eastern Mediterranean)\n  • Shamiana,24 hour international \n    alacarte restaurant\n  • Aquarius, poolside restaurant for \n     resident guests\n  • La Patisserie\n  • Harbour Bar\n  • Sea Lounge\n  • 24- hour in- room dining\n  • Apollo Lounge");
        TA1.setWrapStyleWord(true);
        TA1.setBorder(null);
        TA1.setOpaque(false);
        JSP1.setViewportView(TA1);

        JSP2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        JSP2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        JSP2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JSP2.setOpaque(false);

        TA2.setEditable(false);
        TA2.setColumns(20);
        TA2.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TA2.setRows(5);
        TA2.setText("   WELLNESS   AMENITIES\n\n  • Morning Yoga by the Pool\n  • J iva Spa\n  • Taj Salon\n  • Large outdoor pool\n  • 24-hour fitness centre with \n     Technogym equipment\n  • 24-hour on-call doctor & nurse\n  • Facilit ies for the differently abled");
        TA2.setWrapStyleWord(true);
        TA2.setBorder(null);
        TA2.setOpaque(false);
        JSP2.setViewportView(TA2);

        JSP3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        JSP3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        JSP3.setOpaque(false);

        TA3.setEditable(false);
        TA3.setColumns(20);
        TA3.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        TA3.setRows(5);
        TA3.setText("   OTHER CONVENIENCES\n\n  • Centrallocation in South Mumbai\n  • Located an hour away from the \n    domestic & international airports\n  • 24-hour business centre, with seven \n     meeting rooms fully equipped with \n     modern conferencing facilities, \n     high-speed Wi·Fi,secretarial \n     assistance, interpretation facilities & \n     workstations\n  • Palace rooms,with access to Palace \n     Lounge, butler service & other \n     facilities\n  • Valet parking facility\n  • Golden Keys Concierge & multilingual \n    staff\n  • Traveldesk, car rentalservices, \n     currency exchange, safe deposit \n     lockers & 24-hour laundry\n  • Kids@Taj programmes & baby-sitting\n    services for young guests\n  • Heritage walks for resident guests City \n     tours on request");
        TA3.setWrapStyleWord(true);
        TA3.setBorder(null);
        TA3.setOpaque(false);
        JSP3.setViewportView(TA3);

        javax.swing.GroupLayout JP4Layout = new javax.swing.GroupLayout(JP4);
        JP4.setLayout(JP4Layout);
        JP4Layout.setHorizontalGroup(
            JP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(JP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP4Layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(LBL12)
                        .addGap(624, 624, 624))
                    .addGroup(JP4Layout.createSequentialGroup()
                        .addComponent(JSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(JSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JSP3, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBL11)
                .addGap(396, 396, 396))
        );
        JP4Layout.setVerticalGroup(
            JP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP4Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(LBL11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JSP2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSP3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        JP1.add(JP4);
        JP4.setBounds(0, 1230, 1440, 810);

        JP5.setBackground(new java.awt.Color(255, 255, 255));
        JP5.setOpaque(false);

        LBL16.setFont(new java.awt.Font("Bell MT", 0, 40)); // NOI18N
        LBL16.setText("AWARDS");

        LBL17.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/UNDERLINE.jpg"))); // NOI18N

        LBL18.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/taj award.jpg"))); // NOI18N

        LBL19.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/taj award.jpg"))); // NOI18N

        LBL20.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/taj award.jpg"))); // NOI18N

        LBL21.setFont(new java.awt.Font("Andalus", 0, 12)); // NOI18N
        LBL21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/AWARD 1.jpg"))); // NOI18N

        LBL22.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/AWARD 2.jpg"))); // NOI18N

        LBL23.setFont(new java.awt.Font("Andalus", 0, 30)); // NOI18N
        LBL23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/AWARD 3.jpg"))); // NOI18N

        javax.swing.GroupLayout JP5Layout = new javax.swing.GroupLayout(JP5);
        JP5.setLayout(JP5Layout);
        JP5Layout.setHorizontalGroup(
            JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP5Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP5Layout.createSequentialGroup()
                            .addGap(543, 543, 543)
                            .addComponent(LBL17, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))
                        .addGroup(JP5Layout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(LBL18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LBL19)
                            .addGap(35, 35, 35)))
                    .addGroup(JP5Layout.createSequentialGroup()
                        .addComponent(LBL21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(LBL22)))
                .addGroup(JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP5Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(LBL20)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBL23)
                        .addGap(96, 96, 96))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBL16)
                .addGap(609, 609, 609))
        );
        JP5Layout.setVerticalGroup(
            JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(LBL16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL19)
                    .addComponent(LBL18)
                    .addComponent(LBL20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL21)
                    .addComponent(LBL22)
                    .addComponent(LBL23))
                .addGap(228, 228, 228))
        );

        JP1.add(JP5);
        JP5.setBounds(0, 2050, 1440, 440);

        JBB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/BG.png"))); // NOI18N
        JP1.add(JBB);
        JBB.setBounds(0, 0, 1440, 2511);

        jScrollPane1.setViewportView(JP1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LBL5.setIcon(new ImageIcon(getClass().getResource("/Project_Images/taj1.jpg")));
        
        AnimationClass AC = new AnimationClass();
        AC.jLabelXRight(6, 1027, 40, 2, LBL25);
        
        //public void jLabelXRight(int start, int stop, int delay, int increment, javax.swing.JLabel jLabel)
        //start - The pixel value where the component will start the animation from
        //stop - The pixel value where the component will stop moving
        //delay - Delay between each pixel increment
        //increment - The number of pixels to move
        
        TA1.setBackground(new Color(0, 0, 0, 0));
      //  JSP1.getViewport().setOpaque(false);
        TA2.setBackground(new Color(0, 0, 0, 0));
        JSP2.getViewport().setOpaque(false);
        TA3.setBackground(new Color(0, 0, 0, 0));
        JSP3.getViewport().setOpaque(false);

    }//GEN-LAST:event_formWindowOpened

    private void RB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB5ActionPerformed
        LBL5.setIcon(new ImageIcon(getClass().getResource("/Project_Images/taj5.jpg")));
    }//GEN-LAST:event_RB5ActionPerformed

    private void RB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB4ActionPerformed
        LBL5.setIcon(new ImageIcon(getClass().getResource("/Project_Images/taj4.jpg")));
    }//GEN-LAST:event_RB4ActionPerformed

    private void RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB3ActionPerformed
        LBL5.setIcon(new ImageIcon(getClass().getResource("/Project_Images/taj3.jpg")));
    }//GEN-LAST:event_RB3ActionPerformed

    private void RB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB2ActionPerformed
        LBL5.setIcon(new ImageIcon(getClass().getResource("/Project_Images/taj2.jpg")));
    }//GEN-LAST:event_RB2ActionPerformed

    private void RB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB1ActionPerformed
        LBL5.setIcon(new ImageIcon(getClass().getResource("/Project_Images/taj1.jpg")));
    }//GEN-LAST:event_RB1ActionPerformed

    private void LBL2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL2MouseClicked
        Login_Page LP = new Login_Page();
        LP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LBL2MouseClicked

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        Room_Booking RB = new Room_Booking();
        RB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JLabel JBB;
    private javax.swing.JPanel JP1;
    private javax.swing.JPanel JP2;
    private javax.swing.JPanel JP3;
    private javax.swing.JPanel JP4;
    private javax.swing.JPanel JP5;
    private javax.swing.JScrollPane JSP1;
    private javax.swing.JScrollPane JSP2;
    private javax.swing.JScrollPane JSP3;
    private javax.swing.JLabel LBL1;
    private javax.swing.JLabel LBL10;
    private javax.swing.JLabel LBL11;
    private javax.swing.JLabel LBL12;
    private javax.swing.JLabel LBL16;
    private javax.swing.JLabel LBL17;
    private javax.swing.JLabel LBL18;
    private javax.swing.JLabel LBL19;
    private javax.swing.JLabel LBL2;
    private javax.swing.JLabel LBL20;
    private javax.swing.JLabel LBL21;
    private javax.swing.JLabel LBL22;
    private javax.swing.JLabel LBL23;
    private javax.swing.JLabel LBL25;
    private javax.swing.JLabel LBL4;
    private javax.swing.JLabel LBL5;
    private javax.swing.JLabel LBL6;
    private javax.swing.JLabel LBL7;
    private javax.swing.JLabel LBL8;
    private javax.swing.JLabel LBL9;
    private javax.swing.JRadioButton RB1;
    private javax.swing.JRadioButton RB2;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB4;
    private javax.swing.JRadioButton RB5;
    private javax.swing.JSeparator SP1;
    private javax.swing.JTextArea TA1;
    private javax.swing.JTextArea TA2;
    private javax.swing.JTextArea TA3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
