/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frame;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pranil
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL3 = new javax.swing.JLabel();
        LBL2 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        JPF1 = new javax.swing.JPasswordField();
        LBL4 = new javax.swing.JLabel();
        LBL5 = new javax.swing.JLabel();
        JB1 = new javax.swing.JButton();
        LBL6 = new javax.swing.JLabel();
        LBL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(1440, 855));
        setMinimumSize(new java.awt.Dimension(1440, 855));
        setSize(new java.awt.Dimension(1440, 855));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBL3.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        LBL3.setText("Login");
        getContentPane().add(LBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 110, 40));

        LBL2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/user.jpg"))); // NOI18N
        getContentPane().add(LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 130, 130));

        TF1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        TF1.setText("  User Name / Email ID");
        TF1.setToolTipText("TYPE USER NAME / EMAIL ID HERE");
        TF1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TF1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TF1MouseExited(evt);
            }
        });
        TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF1ActionPerformed(evt);
            }
        });
        getContentPane().add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 330, 50));

        JPF1.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        JPF1.setToolTipText("TYPE PASSWORD HERE");
        getContentPane().add(JPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 330, 50));

        LBL4.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        LBL4.setText("Forget Password ?");
        LBL4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL4MouseClicked(evt);
            }
        });
        getContentPane().add(LBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, 210, -1));

        LBL5.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        LBL5.setText("Create Account");
        LBL5.setToolTipText("CLICK TO CREATE NEW ACCOUNT");
        LBL5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL5MouseClicked(evt);
            }
        });
        getContentPane().add(LBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 610, 180, -1));

        JB1.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        JB1.setText("LOGIN");
        JB1.setToolTipText("CLICK TO LOGIN");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 130, 50));

        LBL6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Button-Back.jpg"))); // NOI18N
        LBL6.setText("jLabel1");
        LBL6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL6MouseClicked(evt);
            }
        });
        getContentPane().add(LBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        LBL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Background Image 1.jpg"))); // NOI18N
        LBL1.setMaximumSize(new java.awt.Dimension(1440, 855));
        LBL1.setMinimumSize(new java.awt.Dimension(1440, 855));
        LBL1.setPreferredSize(new java.awt.Dimension(1440, 855));
        getContentPane().add(LBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LBL5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL5MouseClicked
        Create_Account_Page CA = new Create_Account_Page();
        CA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LBL5MouseClicked

    private void TF1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseClicked
        TF1.setText(""); 
    }//GEN-LAST:event_TF1MouseClicked

    private void TF1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF1MouseExited
        String UNM = TF1.getText();
        if (UNM.isEmpty())
            TF1.setText("  User Name / Email ID");  
    }//GEN-LAST:event_TF1MouseExited

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        String UNM = TF1.getText();
        String PWD = new String (JPF1.getPassword());
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection CON = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
            Statement STM = CON.createStatement();
            String QUE = "SELECT * FROM CUSTOMER_INFORMATION where EmailID = '"+UNM+"' and Password = '"+PWD+"';";
            
            ResultSet RS = STM.executeQuery(QUE);
            if (RS.next())
            {
                JOptionPane.showMessageDialog(this,"Login Successful !!!!","Correct User Name / Password",JOptionPane.INFORMATION_MESSAGE);
                Room_Booking RB = new Room_Booking();
                RB.setVisible(true);
                RB.setAlwaysOnTop(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error", "Please check User Name / Password",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_JB1ActionPerformed

    private void LBL6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL6MouseClicked
        Home_Page HP = new Home_Page();
        HP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LBL6MouseClicked

    private void LBL4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL4MouseClicked
        Forgot_Password_Page FPP = new Forgot_Password_Page();
        FPP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LBL4MouseClicked

    private void TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JPasswordField JPF1;
    private javax.swing.JLabel LBL1;
    private javax.swing.JLabel LBL2;
    private javax.swing.JLabel LBL3;
    private javax.swing.JLabel LBL4;
    private javax.swing.JLabel LBL5;
    private javax.swing.JLabel LBL6;
    private javax.swing.JTextField TF1;
    // End of variables declaration//GEN-END:variables
}
