/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project_Frame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Pranil
 */
public class Room_M_201_209 extends javax.swing.JFrame {

    /**
     * Creates new form Room_101
     */
    public Room_M_201_209() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JB1 = new javax.swing.JButton();
        LBL1 = new javax.swing.JLabel();
        LBL2 = new javax.swing.JLabel();
        LBL3 = new javax.swing.JLabel();
        LBL4 = new javax.swing.JLabel();
        LBL5 = new javax.swing.JLabel();
        LBL6 = new javax.swing.JLabel();
        LBL7 = new javax.swing.JLabel();
        LBL8 = new javax.swing.JLabel();
        LBL9 = new javax.swing.JLabel();
        LBL10 = new javax.swing.JLabel();
        LBL11 = new javax.swing.JLabel();
        LBL12 = new javax.swing.JLabel();
        LBL13 = new javax.swing.JLabel();
        LBL14 = new javax.swing.JLabel();
        LBL15 = new javax.swing.JLabel();
        LBL16 = new javax.swing.JLabel();
        LBL17 = new javax.swing.JLabel();
        LBL18 = new javax.swing.JLabel();
        LBL19 = new javax.swing.JLabel();
        LBL20 = new javax.swing.JLabel();
        LBL21 = new javax.swing.JLabel();
        LBL22 = new javax.swing.JLabel();
        LBL23 = new javax.swing.JLabel();
        LBL24 = new javax.swing.JLabel();
        LBL25 = new javax.swing.JLabel();
        JSP1 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        LBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Room Details");
        setMaximumSize(new java.awt.Dimension(1440, 855));
        setMinimumSize(new java.awt.Dimension(1440, 855));
        setPreferredSize(new java.awt.Dimension(1440, 855));
        setSize(new java.awt.Dimension(1440, 855));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB1.setFont(new java.awt.Font("Andalus", 0, 24)); // NOI18N
        JB1.setText("Book Room ");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 670, 170, 50));

        LBL1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL1.setText("RoomNo");
        getContentPane().add(LBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 30));

        LBL2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL2.setText("CheckInDate");
        getContentPane().add(LBL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 108, 30));

        LBL3.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL3.setText("CheckOutDate");
        getContentPane().add(LBL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 30));

        LBL4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL4.setText("No_Of_Days");
        getContentPane().add(LBL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 169, 30));

        LBL5.setPreferredSize(new java.awt.Dimension(700, 330));
        getContentPane().add(LBL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        LBL6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/Button-Back.jpg"))); // NOI18N
        LBL6.setText("jLabel1");
        LBL6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LBL6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL6MouseClicked(evt);
            }
        });
        getContentPane().add(LBL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        LBL7.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL7.setText("RoomName");
        getContentPane().add(LBL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 460, 40));

        LBL8.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL8.setText("Room No");
        getContentPane().add(LBL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 88, 30));

        LBL9.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL9.setText("Room Name");
        getContentPane().add(LBL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 40));

        LBL10.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL10.setText("Check Out Date");
        getContentPane().add(LBL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        LBL11.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL11.setText("Check In Date");
        getContentPane().add(LBL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 116, 30));

        LBL12.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL12.setText("No of Days of Stay");
        getContentPane().add(LBL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 30));

        LBL13.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL13.setText("Room Details");
        getContentPane().add(LBL13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, 90));

        LBL14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/BATH TUB.png"))); // NOI18N
        LBL14.setToolTipText(" BATH TUB / SHOWER COMBO");
        getContentPane().add(LBL14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        LBL15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/AC.png"))); // NOI18N
        LBL15.setToolTipText("AC");
        getContentPane().add(LBL15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        LBL16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/NO SMOKING.png"))); // NOI18N
        LBL16.setToolTipText("NO SMOKING ROOM");
        getContentPane().add(LBL16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        LBL17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/SOFA.png"))); // NOI18N
        LBL17.setToolTipText("ACCESSIBLE BATH");
        getContentPane().add(LBL17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        LBL18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/TEA.png"))); // NOI18N
        LBL18.setToolTipText("COFFEE & TEA MAKERS");
        getContentPane().add(LBL18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        LBL19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/TELEPHONE.png"))); // NOI18N
        LBL19.setToolTipText("TELEPHONE");
        getContentPane().add(LBL19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        LBL20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/WI-FI.png"))); // NOI18N
        LBL20.setToolTipText("WI-FI");
        getContentPane().add(LBL20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        LBL21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/TV.png"))); // NOI18N
        LBL21.setToolTipText("TV");
        getContentPane().add(LBL21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        LBL22.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        LBL22.setText("Price of Room (in Rs.)");
        LBL22.setToolTipText("TV");
        getContentPane().add(LBL22, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, -1, -1));

        LBL23.setFont(new java.awt.Font("Andalus", 0, 20)); // NOI18N
        LBL23.setToolTipText("TV");
        getContentPane().add(LBL23, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 550, 140, 30));

        LBL24.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL24.setText("Room Type");
        getContentPane().add(LBL24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 30));

        LBL25.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        LBL25.setText("Room Type");
        getContentPane().add(LBL25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 169, 30));

        JSP1.setOpaque(false);

        TA1.setEditable(false);
        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        TA1.setLineWrap(true);
        TA1.setRows(5);
        TA1.setWrapStyleWord(true);
        TA1.setBorder(null);
        TA1.setOpaque(false);
        JSP1.setViewportView(TA1);

        getContentPane().add(JSP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 570, 90));

        LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project_Images/photo.png"))); // NOI18N
        getContentPane().add(LBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        TA1.setBackground(new Color(0, 0, 0, 0));
        JSP1.getViewport().setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        String RN = LBL1.getText();
        String CID = LBL2.getText();
        String COD = LBL3.getText();
        String NODOS = LBL4.getText();
        String PR = LBL23.getText();
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection CON = DriverManager.getConnection("jdbc:mysql://localhost:3306/Hotel_Management_System","root","admin");
            Statement STM = CON.createStatement();
            String QUE = "insert into Booked_Rooms (RoomNo,CheckInDate,CheckOutDate,No_Of_Days) values('" +RN+ "','" +CID+ "','" +COD+ "','" +NODOS+ "');";
            STM.executeUpdate(QUE);
            JOptionPane.showMessageDialog(null, "Room No. "+RN+" is Booked for you"+"\n"+"In Rs. "+PR);
            JOptionPane.showMessageDialog(null, "Thank You !!"+"\n"+"For Booking In Our Hotel");
            Home_Page HP = new Home_Page();
            HP.setVisible(true);
            this.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_JB1ActionPerformed

    private void LBL6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL6MouseClicked
        Room_Booking RB = new Room_Booking();
        RB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LBL6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room_M_201_209.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room_M_201_209.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room_M_201_209.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room_M_201_209.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room_M_201_209().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JScrollPane JSP1;
    private javax.swing.JLabel LBL;
    public javax.swing.JLabel LBL1;
    private javax.swing.JLabel LBL10;
    private javax.swing.JLabel LBL11;
    private javax.swing.JLabel LBL12;
    private javax.swing.JLabel LBL13;
    private javax.swing.JLabel LBL14;
    private javax.swing.JLabel LBL15;
    private javax.swing.JLabel LBL16;
    private javax.swing.JLabel LBL17;
    private javax.swing.JLabel LBL18;
    private javax.swing.JLabel LBL19;
    public javax.swing.JLabel LBL2;
    private javax.swing.JLabel LBL20;
    private javax.swing.JLabel LBL21;
    private javax.swing.JLabel LBL22;
    public javax.swing.JLabel LBL23;
    private javax.swing.JLabel LBL24;
    public javax.swing.JLabel LBL25;
    public javax.swing.JLabel LBL3;
    public javax.swing.JLabel LBL4;
    public javax.swing.JLabel LBL5;
    private javax.swing.JLabel LBL6;
    public javax.swing.JLabel LBL7;
    private javax.swing.JLabel LBL8;
    private javax.swing.JLabel LBL9;
    public javax.swing.JTextArea TA1;
    // End of variables declaration//GEN-END:variables
}
